default_platform(:ios)

platform :ios do

  desc "Efetua o build e envia para o Testflight"
  lane :beta do
    build_app(workspace: "CI-CD-CampusMobile.xcworkspace", scheme: "CI-CD-CampusMobile")    
    upload_to_testflight
  end

  desc "Executa os testes automatizados da aplicação"
  lane :test do
    scan(workspace: "CI-CD-CampusMobile.xcworkspace", scheme: "CI-CD-CampusMobile", output_types: "html")
  end  

end
